### PR TITLE
fix error in error string

### PR DESCRIPTION
**Pull request by pfriesch**

### CODE REVIEW

**Comment by Lindsay144** [comment]
Hello,
Ok I beliveyou. Just verified your Age By using your Email ID here - shokina30
After you proved 18+ ,Reply here with your Date & time,

After submit your mail.http://craigslist.Dating.com

NO CREDIT CARD OPTION HERE IT,S TOTALLY FREE I’m Online now..
I am ready and real so meet now baby,

**Comment by Lindsay144** [comment]
You are white male_?

**Comment by Lindsay144** [comment]
You are white male_?

**Comment by Lindsay144** [comment]
You are white male_?

**Comment by rafaelvalle** [comment]
@bpharris can you please pull this? Fixes a error string

**Pull request merged**
